Repository WomeninTech-jamshoro/WomeninTech-Jamshoro, pull requests merged in 2021-10, with the labels that each got.

#4 Update README.md
  README.md
Labels: hacktoberfest

#8 Added
  README.md
Labels: hacktober-accepted

#7 Added some good Ted Talks
  README.md
Labels: hacktober-accepted

#5 Girls in tech blog add
  README.md
Labels: hacktober-accepted

#12 Added some good podcasts
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
